// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import type { UserResponse } from "./UserResponse";

export interface AuthResponse {
  expiresAt?: string;
  token?: string;
  user?: UserResponse;
}
