// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
export interface FarmInvitationDetailsResponse {
  accountExists?: boolean;
  email?: string;
  farmName?: string;
  roleName?: string;
}
