// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
export interface FarmResponse {
  addressLine?: string | null;
  city?: string | null;
  country?: string | null;
  createdAt?: string;
  id?: string | number;
  latitude?: string | number;
  longitude?: string | number;
  name?: string;
  postalCode?: string | null;
  roleName?: string;
  state?: string | null;
  updatedAt?: string;
}
