// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import type { User } from "./User";

export interface RefreshToken {
  createdAt?: string;
  expiresAt?: string;
  id?: string | number;
  replacedByHash?: string | null;
  revokedAt?: string | null;
  tokenHash?: string;
  user?: User;
  userId?: string | number;
}
