// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import type { RefreshToken } from "./RefreshToken";

export interface User {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: string | number;
  isActive?: boolean;
  lastName?: string;
  password?: string;
  refreshTokens?: RefreshToken[];
  updatedAt?: string;
}
