// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
export interface UserResponse {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: string | number;
  isActive?: boolean;
  lastName?: string;
  updatedAt?: string;
}
