// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { LoginRequest } from "../models/request/LoginRequest";
import type { RegisterRequest } from "../models/request/RegisterRequest";
import type { AuthResponse } from "../models/response/AuthResponse";
import type { UserResponse } from "../models/response/UserResponse";

class AuthApiClient {
  async loginAsync(request: LoginRequest): Promise<AuthResponse> {
    const response = await httpClient.post<AuthResponse>("/api/Auth/login", request);
    return response.data;
  }

  async logoutAsync(): Promise<void> {
    await httpClient.post("/api/Auth/logout", undefined);
  }

  async meAsync(): Promise<UserResponse> {
    const response = await httpClient.get<UserResponse>("/api/Auth/me");
    return response.data;
  }

  async refreshAsync(): Promise<AuthResponse> {
    const response = await httpClient.post<AuthResponse>("/api/Auth/refresh", undefined);
    return response.data;
  }

  async signUpAsync(request: RegisterRequest): Promise<AuthResponse> {
    const response = await httpClient.post<AuthResponse>("/api/Auth/SignUp", request);
    return response.data;
  }
}

export const AuthApi = new AuthApiClient();
