// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { LoginRequest } from "../models/request/LoginRequest";
import type { RegisterRequest } from "../models/request/RegisterRequest";
import type { AuthResponse } from "../models/response/AuthResponse";
import type { User } from "../models/response/User";

class AuthApiClient {
  async Login(request: LoginRequest): Promise<AuthResponse> {
    const response = await httpClient.post<AuthResponse>("/api/Auth/login", request);
    return response.data;
  }

  async Logout(): Promise<void> {
    await httpClient.post("/api/Auth/logout", undefined);
  }

  async Me(): Promise<User> {
    const response = await httpClient.get<User>("/api/Auth/me");
    return response.data;
  }

  async Refresh(): Promise<AuthResponse> {
    const response = await httpClient.post<AuthResponse>("/api/Auth/refresh", undefined);
    return response.data;
  }

  async Register(request: RegisterRequest): Promise<AuthResponse> {
    const response = await httpClient.post<AuthResponse>("/api/Auth/register", request);
    return response.data;
  }
}

export const AuthApi = new AuthApiClient();
