// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { FarmRoleTypeResponse } from "../models/response/FarmRoleTypeResponse";

class FarmRoleTypesApiClient {
  async getAllAsync(): Promise<FarmRoleTypeResponse[]> {
    const response = await httpClient.get<FarmRoleTypeResponse[]>("/api/FarmRoleTypes");
    return response.data;
  }
}

export const FarmRoleTypesApi = new FarmRoleTypesApiClient();
