// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { CreateFarmInvitationRequest } from "../models/request/CreateFarmInvitationRequest";
import type { FarmInvitationDetailsResponse } from "../models/response/FarmInvitationDetailsResponse";

class FarmInvitationsApiClient {
  async acceptAsync(token: string): Promise<FarmInvitationDetailsResponse> {
    const response = await httpClient.post<FarmInvitationDetailsResponse>(`/api/FarmInvitations/${token}/accept`, undefined);
    return response.data;
  }

  async createAsync(request: CreateFarmInvitationRequest): Promise<void> {
    await httpClient.post("/api/FarmInvitations", request);
  }

  async getByTokenAsync(token: string): Promise<FarmInvitationDetailsResponse> {
    const response = await httpClient.get<FarmInvitationDetailsResponse>(`/api/FarmInvitations/${token}`);
    return response.data;
  }
}

export const FarmInvitationsApi = new FarmInvitationsApiClient();
