// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { CreateFarmRequest } from "../models/request/CreateFarmRequest";
import type { FarmResponse } from "../models/response/FarmResponse";

class FarmApiClient {
  async createAsync(request: CreateFarmRequest): Promise<FarmResponse> {
    const response = await httpClient.post<FarmResponse>("/api/Farm", request);
    return response.data;
  }

  async getAllAsync(): Promise<FarmResponse[]> {
    const response = await httpClient.get<FarmResponse[]>("/api/Farm");
    return response.data;
  }
}

export const FarmApi = new FarmApiClient();
