// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { UserResponse } from "../models/response/UserResponse";

class UsersApiClient {
  async getAllAsync(): Promise<UserResponse[]> {
    const response = await httpClient.get<UserResponse[]>("/api/Users");
    return response.data;
  }
}

export const UsersApi = new UsersApiClient();
