// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
import { httpClient } from "./httpClient";
import type { User } from "../models/response/User";

class UsersApiClient {
  async GetAll(): Promise<User[]> {
    const response = await httpClient.get<User[]>("/api/Users");
    return response.data;
  }
}

export const UsersApi = new UsersApiClient();
