using System.Text;
using Npgsql;

namespace HomeSteadier.Database;

public class TableScriptGenerationService
{
    // Owned by DbUp (see DatabaseMigrationService), not a modeled table.
    private static readonly string[] ExcludedTables = ["migrations"];

    public async Task<TableScriptGenerationResult> GenerateTableScriptsAsync(string connectionString, string outputDirectory)
    {
        var result = new TableScriptGenerationResult();

        try
        {
            Directory.CreateDirectory(outputDirectory);

            await using var connection = new NpgsqlConnection(connectionString);
            await connection.OpenAsync();

            var tables = await GetTableNamesAsync(connection);

            foreach (var table in tables)
            {
                if (ExcludedTables.Contains(table, StringComparer.OrdinalIgnoreCase))
                {
                    result.Skipped.Add(table);
                    continue;
                }

                var script = await BuildCreateTableScriptAsync(connection, table);
                var filePath = Path.Combine(outputDirectory, $"{table}.sql");
                var isNew = !File.Exists(filePath);
                var existingScript = isNew ? null : await File.ReadAllTextAsync(filePath);

                if (existingScript == script)
                {
                    result.Unchanged.Add(table);
                    continue;
                }

                await File.WriteAllTextAsync(filePath, script);
                (isNew ? result.Created : result.Updated).Add(table);
            }

            foreach (var file in Directory.GetFiles(outputDirectory, "*.sql"))
            {
                var tableName = Path.GetFileNameWithoutExtension(file);
                if (!tables.Contains(tableName, StringComparer.OrdinalIgnoreCase))
                {
                    File.Delete(file);
                    result.Removed.Add(tableName);
                }
            }

            result.Success = true;
            result.Message = "Table scripts generated successfully!";
        }
        catch (Exception ex)
        {
            result.Success = false;
            result.Error = ex.Message;
            result.Message = "Error generating table scripts";
        }

        return result;
    }

    private static async Task<List<string>> GetTableNamesAsync(NpgsqlConnection connection)
    {
        const string sql = """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
            ORDER BY table_name;
            """;

        var tables = new List<string>();
        await using var command = new NpgsqlCommand(sql, connection);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            tables.Add(reader.GetString(0));

        return tables;
    }

    private static async Task<string> BuildCreateTableScriptAsync(NpgsqlConnection connection, string table)
    {
        var columns = await GetColumnDefinitionsAsync(connection, table);
        var constraints = await GetConstraintDefinitionsAsync(connection, table);
        var indexes = await GetIndexDefinitionsAsync(connection, table, constraints.Select(c => c.Name));
        var identityColumns = await GetIdentityColumnsAsync(connection, table);

        var sb = new StringBuilder();
        sb.AppendLine($"-- Auto-generated by 'database gen'. Reflects the live schema for \"{table}\" — do not hand-edit.");
        sb.AppendLine($"CREATE TABLE IF NOT EXISTS \"public\".\"{table}\" (");

        var lines = columns
            .Select(c => FormatColumnLine(c, identityColumns.GetValueOrDefault(c.Name)))
            .Concat(constraints.Select(c => $"    CONSTRAINT \"{c.Name}\" {c.Definition}"))
            .ToList();

        sb.AppendLine(string.Join(",\n", lines));
        sb.AppendLine(");");

        foreach (var index in indexes)
        {
            sb.AppendLine();
            sb.AppendLine(index);
        }

        return sb.ToString();
    }

    private static string FormatColumnLine(ColumnDefinition column, string? identityKind)
    {
        var notNull = column.NotNull ? " NOT NULL" : "";

        // Columns backed by an owned sequence (SERIAL, or native IDENTITY) round-trip through the
        // sequence-less GENERATED ... AS IDENTITY clause instead of a nextval() default, since the
        // referenced sequence itself isn't (re)created by this script.
        if (identityKind != null)
        {
            var clause = identityKind == "a" ? "GENERATED ALWAYS AS IDENTITY" : "GENERATED BY DEFAULT AS IDENTITY";
            return $"    \"{column.Name}\" {column.Type}{notNull} {clause}";
        }

        var defaultClause = column.Default != null ? $" DEFAULT {column.Default}" : "";
        return $"    \"{column.Name}\" {column.Type}{notNull}{defaultClause}";
    }

    private static async Task<Dictionary<string, string>> GetIdentityColumnsAsync(NpgsqlConnection connection, string table)
    {
        const string sql = """
            SELECT a.attname, a.attidentity::text
            FROM pg_depend d
            JOIN pg_class seq ON seq.oid = d.objid AND seq.relkind = 'S'
            JOIN pg_attribute a ON a.attrelid = d.refobjid AND a.attnum = d.refobjsubid
            JOIN pg_class c ON c.oid = d.refobjid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE d.deptype IN ('a', 'i')
              AND c.relname = @table
              AND n.nspname = 'public';
            """;

        var identityColumns = new Dictionary<string, string>();
        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("table", table);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            identityColumns[reader.GetString(0)] = reader.GetString(1);

        return identityColumns;
    }

    private static async Task<List<ColumnDefinition>> GetColumnDefinitionsAsync(NpgsqlConnection connection, string table)
    {
        const string sql = """
            SELECT a.attname AS column_name,
                   format_type(a.atttypid, a.atttypmod) AS data_type,
                   a.attnotnull AS not_null,
                   pg_get_expr(ad.adbin, ad.adrelid) AS default_value
            FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
            WHERE c.relname = @table
              AND n.nspname = 'public'
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum;
            """;

        var columns = new List<ColumnDefinition>();
        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("table", table);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            columns.Add(new ColumnDefinition(
                reader.GetString(0),
                reader.GetString(1),
                reader.GetBoolean(2),
                reader.IsDBNull(3) ? null : reader.GetString(3)));
        }

        return columns;
    }

    private static async Task<List<ConstraintDefinition>> GetConstraintDefinitionsAsync(NpgsqlConnection connection, string table)
    {
        const string sql = """
            SELECT con.conname AS constraint_name,
                   pg_get_constraintdef(con.oid) AS definition
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = @table
              AND n.nspname = 'public'
            ORDER BY con.contype, con.conname;
            """;

        var constraints = new List<ConstraintDefinition>();
        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("table", table);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            constraints.Add(new ConstraintDefinition(reader.GetString(0), reader.GetString(1)));

        return constraints;
    }

    private static async Task<List<string>> GetIndexDefinitionsAsync(NpgsqlConnection connection, string table, IEnumerable<string> constraintNames)
    {
        const string sql = """
            SELECT indexname, indexdef
            FROM pg_indexes
            WHERE schemaname = 'public' AND tablename = @table
            ORDER BY indexname;
            """;

        var constraintNameSet = new HashSet<string>(constraintNames, StringComparer.OrdinalIgnoreCase);
        var indexes = new List<string>();
        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("table", table);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            var indexName = reader.GetString(0);
            // Constraint-backed indexes (primary key / unique) are already emitted as CONSTRAINT clauses.
            if (constraintNameSet.Contains(indexName))
                continue;

            var indexDef = reader.GetString(1) + ";";
            indexDef = indexDef.Replace("CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ");
            indexDef = indexDef.Replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ");
            indexes.Add(indexDef);
        }

        return indexes;
    }

    private sealed record ColumnDefinition(string Name, string Type, bool NotNull, string? Default);

    private sealed record ConstraintDefinition(string Name, string Definition);
}

public class TableScriptGenerationResult
{
    public bool Success { get; set; }
    public string? Error { get; set; }
    public string Message { get; set; } = string.Empty;
    public List<string> Created { get; set; } = [];
    public List<string> Updated { get; set; } = [];
    public List<string> Unchanged { get; set; } = [];
    public List<string> Removed { get; set; } = [];
    public List<string> Skipped { get; set; } = [];
}
