/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLivestockRouteImport } from './routes/_authenticated.livestock'
import { Route as AuthenticatedInviteMemberRouteImport } from './routes/_authenticated.invite-member'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedGardenRouteImport } from './routes/_authenticated.garden'
import { Route as AuthenticatedConstructionRouteImport } from './routes/_authenticated.construction'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated.change-password'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLivestockRoute = AuthenticatedLivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInviteMemberRoute =
  AuthenticatedInviteMemberRouteImport.update({
    id: '/invite-member',
    path: '/invite-member',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGardenRoute = AuthenticatedGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConstructionRoute =
  AuthenticatedConstructionRouteImport.update({
    id: '/construction',
    path: '/construction',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/construction': typeof AuthenticatedConstructionRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/home': typeof AuthenticatedHomeRoute
  '/invite-member': typeof AuthenticatedInviteMemberRoute
  '/livestock': typeof AuthenticatedLivestockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/construction': typeof AuthenticatedConstructionRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/home': typeof AuthenticatedHomeRoute
  '/invite-member': typeof AuthenticatedInviteMemberRoute
  '/livestock': typeof AuthenticatedLivestockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/construction': typeof AuthenticatedConstructionRoute
  '/_authenticated/garden': typeof AuthenticatedGardenRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/invite-member': typeof AuthenticatedInviteMemberRoute
  '/_authenticated/livestock': typeof AuthenticatedLivestockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/change-password'
    | '/construction'
    | '/garden'
    | '/home'
    | '/invite-member'
    | '/livestock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/change-password'
    | '/construction'
    | '/garden'
    | '/home'
    | '/invite-member'
    | '/livestock'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/change-password'
    | '/_authenticated/construction'
    | '/_authenticated/garden'
    | '/_authenticated/home'
    | '/_authenticated/invite-member'
    | '/_authenticated/livestock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/livestock': {
      id: '/_authenticated/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof AuthenticatedLivestockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invite-member': {
      id: '/_authenticated/invite-member'
      path: '/invite-member'
      fullPath: '/invite-member'
      preLoaderRoute: typeof AuthenticatedInviteMemberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garden': {
      id: '/_authenticated/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof AuthenticatedGardenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/construction': {
      id: '/_authenticated/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof AuthenticatedConstructionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedConstructionRoute: typeof AuthenticatedConstructionRoute
  AuthenticatedGardenRoute: typeof AuthenticatedGardenRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInviteMemberRoute: typeof AuthenticatedInviteMemberRoute
  AuthenticatedLivestockRoute: typeof AuthenticatedLivestockRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedConstructionRoute: AuthenticatedConstructionRoute,
  AuthenticatedGardenRoute: AuthenticatedGardenRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInviteMemberRoute: AuthenticatedInviteMemberRoute,
  AuthenticatedLivestockRoute: AuthenticatedLivestockRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
