// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
export interface CreateFarmInvitationRequest {
  email: string;
  farmId: string | number;
  farmRoleTypeId: string | number;
}
