// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
export interface CreateFarmRequest {
  addressLine?: string | null;
  city?: string | null;
  country?: string | null;
  latitude: string | number;
  longitude: string | number;
  name: string;
  postalCode?: string | null;
  state?: string | null;
}
