// Auto-generated by 'packages gen' from the API's OpenAPI document. Do not hand-edit.
export interface RegisterRequest {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}
