-- Auto-generated by 'database gen'. Reflects the live schema for "crop_types" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."crop_types" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(100) NOT NULL,
    "genus" character varying(100) NOT NULL,
    "family" character varying(100) NOT NULL,
    CONSTRAINT "crop_types_pkey" PRIMARY KEY (id)
);
