-- Auto-generated by 'database gen'. Reflects the live schema for "crop_types" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."crop_types" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(100) NOT NULL,
    "genus" character varying(100) NOT NULL,
    "family" character varying(100) NOT NULL,
    "spacing_inches" integer,
    "sunlight_requirement_hours" numeric(6,2),
    CONSTRAINT "crop_types_pkey" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_crop_types_name ON public.crop_types USING btree (name);
