-- Auto-generated by 'database gen'. Reflects the live schema for "farm_invitations" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."farm_invitations" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "farm_id" integer NOT NULL,
    "farm_role_type_id" integer NOT NULL,
    "email" character varying(255) NOT NULL,
    "invited_by_user_id" integer NOT NULL,
    "token_hash" character varying(128) NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "accepted_at" timestamp with time zone,
    CONSTRAINT "farm_invitations_farm_id_fkey" FOREIGN KEY (farm_id) REFERENCES farms(id) ON DELETE CASCADE,
    CONSTRAINT "farm_invitations_farm_role_type_id_fkey" FOREIGN KEY (farm_role_type_id) REFERENCES farm_role_types(id),
    CONSTRAINT "farm_invitations_invited_by_user_id_fkey" FOREIGN KEY (invited_by_user_id) REFERENCES users(id),
    CONSTRAINT "farm_invitations_pkey" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_farm_invitations_farm_id_email ON public.farm_invitations USING btree (farm_id, email);

CREATE UNIQUE INDEX IF NOT EXISTS ix_farm_invitations_token_hash ON public.farm_invitations USING btree (token_hash);
