-- Auto-generated by 'database gen'. Reflects the live schema for "farm_role_types" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."farm_role_types" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(50) NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "farm_role_types_pkey" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_farm_role_types_name ON public.farm_role_types USING btree (name);
