-- Auto-generated by 'database gen'. Reflects the live schema for "farm" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."farm" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(255) NOT NULL,
    "address_line" character varying(255),
    "city" character varying(100),
    "state" character varying(100),
    "postal_code" character varying(20),
    "country" character varying(100),
    "latitude" numeric(9,6) NOT NULL,
    "longitude" numeric(9,6) NOT NULL,
    "timezone" character varying(64) NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "farm_pkey" PRIMARY KEY (id)
);
