-- Auto-generated by 'database gen'. Reflects the live schema for "garden_bed" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."garden_bed" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(255) NOT NULL,
    "length" numeric(6,2) NOT NULL,
    "width" numeric(6,2) NOT NULL,
    "sunlight_hours" numeric(6,2) NOT NULL,
    CONSTRAINT "garden_bed_pkey" PRIMARY KEY (id)
);
