-- Auto-generated by 'database gen'. Reflects the live schema for "garden_bed_crops" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."garden_bed_crops" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "garden_bed_id" integer NOT NULL,
    "crop_type_id" integer NOT NULL,
    CONSTRAINT "garden_bed_crops_crop_type_id_fkey" FOREIGN KEY (crop_type_id) REFERENCES crop_types(id) ON DELETE CASCADE,
    CONSTRAINT "garden_bed_crops_garden_bed_id_fkey" FOREIGN KEY (garden_bed_id) REFERENCES garden_bed(id) ON DELETE CASCADE,
    CONSTRAINT "garden_bed_crops_pkey" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_garden_bed_crops_crop_type_id ON public.garden_bed_crops USING btree (crop_type_id);

CREATE INDEX IF NOT EXISTS ix_garden_bed_crops_garden_bed_id ON public.garden_bed_crops USING btree (garden_bed_id);
