-- Auto-generated by 'database gen'. Reflects the live schema for "password_reset_tokens" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."password_reset_tokens" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "token_hash" character varying(128) NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "consumed_at" timestamp with time zone,
    CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_password_reset_tokens_token_hash ON public.password_reset_tokens USING btree (token_hash);

CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_user_id ON public.password_reset_tokens USING btree (user_id);
