-- Auto-generated by 'database gen'. Reflects the live schema for "refresh_tokens" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."refresh_tokens" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "token_hash" character varying(128) NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" timestamp with time zone,
    "replaced_by_hash" character varying(128),
    CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_token_hash ON public.refresh_tokens USING btree (token_hash);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id);
