-- Auto-generated by 'database gen'. Reflects the live schema for "user_farms" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."user_farms" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "farm_id" integer NOT NULL,
    "role" character varying(50) NOT NULL DEFAULT 'owner'::character varying,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "user_farms_farm_id_fkey" FOREIGN KEY (farm_id) REFERENCES farm(id) ON DELETE CASCADE,
    CONSTRAINT "user_farms_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "user_farms_pkey" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_user_farms_farm_id ON public.user_farms USING btree (farm_id);

CREATE INDEX IF NOT EXISTS ix_user_farms_user_id ON public.user_farms USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS ix_user_farms_user_id_farm_id ON public.user_farms USING btree (user_id, farm_id);
