-- Auto-generated by 'database gen'. Reflects the live schema for "users" — do not hand-edit.
CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" character varying(255) NOT NULL,
    "password" character varying(255) NOT NULL,
    "first_name" character varying(100) NOT NULL,
    "last_name" character varying(100) NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_active" boolean NOT NULL DEFAULT true,
    CONSTRAINT "users_pkey" PRIMARY KEY (id),
    CONSTRAINT "users_email_key" UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS ix_users_email ON public.users USING btree (email);
